# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180219_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinfo',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
