# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_saleinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dealership',
            field=models.CharField(max_length=100),
        ),
    ]
